spring:
  datasource:
    url: jdbc:postgresql://user-db:5432/user_service
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8180/realms/microservice-realm
          jwk-set-uri: http://keycloak:8180/realms/microservice-realm/protocol/openid-connect/certs
  rabbitmq:
    host: rabbitmq
    port: 5672

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

logging:
  level:
    root: WARN
    com.microservice: INFO
