spring:
  datasource:
    url: jdbc:postgresql://product-db:5432/product_service
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: WARN
    com.microservice: INFO
